# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - nuget restore -Verbosity detailed

version: 1.0.{build}

os: Windows Server 2012 R2

configuration: debug

platform: Any CPU

nuget:
  account_feed: true
  project_feed: true

build:
  publish_wap: true
  verbosity: minimal

test:
  assemblies: CommandLine

artifacts:
- path: gfilter.zip
  name: GFilterImporter

- path: 'GFilterImporter\bin\Debug\*'
  name: executables
  type: zip

deploy: off 
